# Generated by Django 4.2.23 on 2025-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourceversion',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resourceversion',
            name='file_mime',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
